Repository Samsung/TAU-Design-Editor, pull requests merged in 2019-08, with the labels that each got.

#256 Remove flickering effect from DE saving
  brackets-extension/src/command-tau-preview.js
  design-editor/src/brackets/brackets-editor.js
  design-editor/src/pane/design-editor-element.js
  design-editor/src/pane/model-manager.js
  design-editor/src/utils/iframe.js
Labels: in review

#263 Enlarge scrollable containers on focus
  design-editor/src/pane/design-editor-element.js
  design-editor/src/panel/property/component/component-element.js
  design-editor/src/system/stage-manager.js
Labels: in review

#282 Enable element removing after select it indirectly
  design-editor/src/pane/element-selector.js
  design-editor/src/panel/property/structure/structure-element.js
Labels: in review

#285 Enable adding the text and image widgets to header
  tau-component-packages/components/header/package.json
Labels: in review

#290 TextInput: Fix for moving text input component
  closet-default-component-packages/components/input-number/package.json
  closet-default-component-packages/components/input-password/package.json
  closet-default-component-packages/components/input-text/package.json
  design-editor/src/pane/design-editor-element.js
Labels: in review

#306 Remove the Behavior->Events->animation
  design-editor/src/panel/property/behavior/behavior-item.html
Labels: in review

#294 Call refresh method after changing style
  design-editor/src/pane/design-editor-element.js
Labels: 1.0, in review

#311 Fill attributes panel elements with computed value
  design-editor/src/panel/property/attribute/attribute-element.js
Labels: important, in review
