Repository Samsung/TAU-Design-Editor, pull requests merged in 2019-07, with the labels that each got.

#107 Hide scrollbar in document preview
  design-editor/src/panel/preview/preview-element.js
  design-editor/src/system/libraries/css-library.js
  design-editor/src/templates/preview-helper.css
  design-editor/src/utils/utils.js
Labels: in review

#110 Add `#main` to preview document
  design-editor/src/panel/preview/preview-element.js
  design-editor/src/system/libraries/js-library.js
Labels: PR ready, bug, in review

#122 Enable preview refreshing in demo mode
  brackets-extension/src/command-tau-preview.js
  design-editor/src/pane/design-editor-element.js
  design-editor/src/system/stage-manager.js
Labels: 1.0, in review

#147 Fix for back button in design editor preview
  design-editor/src/panel/preview/preview-element.js
Labels: PR ready

#150 helper.js and fs-extra fixes
  design-editor/src/pane/design-editor.js
  design-editor/src/system/libraries/library.js
  design-editor/src/templates/back-button-support.js
  vsc-extension/design-editor/libs/fs-extra.js
Labels: in review

#149 Disable selecting and dragging content in preview
  design-editor/src/templates/preview-helper.css
Labels: PR ready

#163 Fix fs-extra, hide scrollbar in DE
  design-editor/src/panel/property/component/component-element.js
  design-editor/src/system/libraries/library.js
  design-editor/src/templates/preview-helper.css
  vsc-extension/design-editor/libs/fs-extra.js
Labels: in review

#180 Enable ToggleSlider drag&drop funcionality
  tau-component-packages/components/content/package.json
  tau-component-packages/components/header/package.json
  tau-component-packages/components/listitem/package.json
  tau-component-packages/components/popup-content/package.json
  tau-component-packages/components/section/package.json
Labels: in review

#195 Hide DE icon while going to Live Preview
  design-editor/src/system/stage-manager.js
Labels: important, in review

#148 Add data-id and attributes to container of widget if it exists
  design-editor/src/pane/design-editor-element.js
Labels: in review

#194 Set placeholder to give image height and width
  closet-component-packages/components/image/package.json
Labels: in review

#203 Fix file saving into Assistant View
  brackets-extension/design-editor/libs/assistant-view/assistant-view-element.js
  brackets-extension/design-editor/libs/assistant-view/assistant-view-manager.js
  brackets-extension/design-editor/libs/fs-extra.js
  brackets-extension/design-editor/libs/fs-mock.js
  design-editor/src/system/assistant/assistant-manager.js
  design-editor/src/system/libraries/library.js
  design-editor/src/system/panel-manager.js
  design-editor/src/system/project-manager.js
Labels: in review

#201 Trigger rotaryevent on mousewheel
  design-editor/src/pane/design-editor-element.js
Labels: in review

#202 Disable adding external resources by widget
  design-editor/src/pane/design-editor-element.js
  design-editor/src/panel/property/component/component-element.js
Labels: in review

#185 Disable the widget
  tau-component-packages/package.js
Labels: in review

#167 Enable possibility to set directives of widget resize.
  design-editor/src/pane/interaction.js
  tau-component-packages/components/slider/package.json
Labels: in review

#211 Remove edit mode toggle
  design-editor/src/panel/toolbar-element.html
Labels: in review

#165 Parsing HTML references in temporary file
  design-editor/src/panel/preview/preview-element.js
  design-editor/src/utils/utils.js
Labels: in review

#218 Fix changing dimensions after dragging element
  design-editor/src/pane/interaction.js
Labels: in review

#225 ToggleSlider: changing visibility only for mobile profile.
  tau-component-packages/components/toggleslider/package.json
Labels: in review

#27 Get rid of Atom related cson files/tasks
  contents/Gruntfile.js
  contents/package.json
  design-editor/keymaps/keymap.cson
  design-editor/menus/closet.cson
  tau-component-packages/libs/closet/1.0.0/components/analog-watch/package.cson
  tau-component-packages/libs/closet/1.0.0/components/button/package.cson
  tau-component-packages/libs/closet/1.0.0/components/image/package.cson
  tau-component-packages/libs/closet/1.0.0/components/page/package.cson
  tau-component-packages/libs/closet/1.0.0/components/poll-list/package.cson
  tau-component-packages/libs/closet/1.0.0/components/tau-circle-progress/package.cson
  tau-component-packages/libs/closet/1.0.0/components/video/package.cson
Labels: in review

#236 Fix Graph in preview mode on wearable
  design-editor/src/templates/circle-helper.js
Labels: in review

#246 Fix behaviour panel - data exposing problem
  design-editor/src/panel/property/behavior/behavior-element.js
  design-editor/src/panel/property/behavior/behaviour-element.spec.js
Labels: in review
